{% set name = "thorlabs-apt-protocol" %}
{% set version = "29.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: caf99ff88043d2f070196903c09299bc8d8ec9da063be4c3c3832fe829772d32

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - flit
  run:
    - python >=3.6

test:
  imports:
    - thorlabs_apt_protocol
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/yaq/thorlabs-apt-protocol
  summary: Functional implementation of the thorlabs APT protocol
  dev_url: https://gitlab.com/yaq/thorlabs-apt-protocol
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
